baseURL = 'https://example.org/'
# baseURL = "https://m02uku.github.io/my-portfolio-hugo/"
languageCode = 'ja'
title = 'Portfolio'

[module]
proxy = "direct"

[[module.imports]]
path = "github.com/google/docsy"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]

# Enable the left sidebar
enableSideMenu = true

# UI
[params.ui]
showLightDarkModeMenu = true

# community
[params.links]
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/m02uku"
icon = "fab fa-github"


[params.print]
disable_toc = true

[outputs]
section = ["HTML", "RSS", "print"]

# External links on the top menu
# [[menu.main]]
# name = "GitHub"
# weight = 50
# url = "https://github.com/google/docsy/"
