baseURL = 'https://example.org/'
languageCode = 'en'
title = '^^b'

[module]
proxy = "direct"

[[module.imports]]
path = "github.com/google/docsy"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# community
[params.links]
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/m02uku/my-portfolio-hugo"
icon = "fab fa-github"

[outputs]
section = ["HTML", "RSS", "print"]

# UI
[params]
[params.ui]
showLightDarkModeMenu = true

# External links on the top menu
[[menu.main]]
# name = "GitHub"
# weight = 50
# url = "https://github.com/google/docsy/"

[params.print]
disable_toc = true
